// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebbAPI.Data;

#nullable disable

namespace WebbAPI.Migrations
{
    [DbContext(typeof(SystemDbContext))]
    [Migration("20250425123224_InitSystemDb3")]
    partial class InitSystemDb3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebbAPI.Modules.Interests", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Writing and debugging code.",
                            Interest = "Programming"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Capturing moments with a camera.",
                            Interest = "Photography"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Making delicious meals.",
                            Interest = "Cooking"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Playing video games competitively or for fun.",
                            Interest = "Gaming"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Enjoying books and novels.",
                            Interest = "Reading"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Listening to and creating music.",
                            Interest = "Music"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Exploring new places and cultures.",
                            Interest = "Traveling"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Staying active and healthy.",
                            Interest = "Fitness"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Growing and taking care of plants.",
                            Interest = "Gardening"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Exploring the latest in tech.",
                            Interest = "Technology"
                        });
                });

            modelBuilder.Entity("WebbAPI.Modules.Links", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "InterestId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InterestId = 1,
                            Link = "https://dev.to/alice",
                            PersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            InterestId = 2,
                            Link = "https://unsplash.com/bob",
                            PersonId = 2
                        },
                        new
                        {
                            Id = 3,
                            InterestId = 3,
                            Link = "https://recipes.com/clara",
                            PersonId = 3
                        },
                        new
                        {
                            Id = 4,
                            InterestId = 4,
                            Link = "https://twitch.tv/davidplays",
                            PersonId = 4
                        },
                        new
                        {
                            Id = 5,
                            InterestId = 5,
                            Link = "https://goodreads.com/ella",
                            PersonId = 5
                        },
                        new
                        {
                            Id = 6,
                            InterestId = 6,
                            Link = "https://soundcloud.com/felix",
                            PersonId = 6
                        },
                        new
                        {
                            Id = 7,
                            InterestId = 7,
                            Link = "https://travelblog.com/grace",
                            PersonId = 7
                        },
                        new
                        {
                            Id = 8,
                            InterestId = 8,
                            Link = "https://fitgram.com/harry",
                            PersonId = 8
                        },
                        new
                        {
                            Id = 9,
                            InterestId = 9,
                            Link = "https://gardenershub.com/isla",
                            PersonId = 9
                        },
                        new
                        {
                            Id = 10,
                            InterestId = 10,
                            Link = "https://techtrends.com/jack",
                            PersonId = 10
                        });
                });

            modelBuilder.Entity("WebbAPI.Modules.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Firstname = "Alice",
                            Lastname = "Smith",
                            Phone = "0701111111"
                        },
                        new
                        {
                            Id = 2,
                            Firstname = "Bob",
                            Lastname = "Johnson",
                            Phone = "0702222222"
                        },
                        new
                        {
                            Id = 3,
                            Firstname = "Clara",
                            Lastname = "Williams",
                            Phone = "0703333333"
                        },
                        new
                        {
                            Id = 4,
                            Firstname = "David",
                            Lastname = "Brown",
                            Phone = "0704444444"
                        },
                        new
                        {
                            Id = 5,
                            Firstname = "Ella",
                            Lastname = "Jones",
                            Phone = "0705555555"
                        },
                        new
                        {
                            Id = 6,
                            Firstname = "Felix",
                            Lastname = "Garcia",
                            Phone = "0706666666"
                        },
                        new
                        {
                            Id = 7,
                            Firstname = "Grace",
                            Lastname = "Miller",
                            Phone = "0707777777"
                        },
                        new
                        {
                            Id = 8,
                            Firstname = "Harry",
                            Lastname = "Davis",
                            Phone = "0708888888"
                        },
                        new
                        {
                            Id = 9,
                            Firstname = "Isla",
                            Lastname = "Martinez",
                            Phone = "0709999999"
                        },
                        new
                        {
                            Id = 10,
                            Firstname = "Jack",
                            Lastname = "Taylor",
                            Phone = "0701010101"
                        });
                });

            modelBuilder.Entity("WebbAPI.Modules.PersonInterests", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.HasKey("PersonId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("PersonInterests");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            InterestId = 1
                        },
                        new
                        {
                            PersonId = 2,
                            InterestId = 2
                        },
                        new
                        {
                            PersonId = 3,
                            InterestId = 3
                        },
                        new
                        {
                            PersonId = 4,
                            InterestId = 4
                        },
                        new
                        {
                            PersonId = 5,
                            InterestId = 5
                        },
                        new
                        {
                            PersonId = 6,
                            InterestId = 6
                        },
                        new
                        {
                            PersonId = 7,
                            InterestId = 7
                        },
                        new
                        {
                            PersonId = 8,
                            InterestId = 8
                        },
                        new
                        {
                            PersonId = 9,
                            InterestId = 9
                        },
                        new
                        {
                            PersonId = 10,
                            InterestId = 10
                        });
                });

            modelBuilder.Entity("WebbAPI.Modules.Links", b =>
                {
                    b.HasOne("WebbAPI.Modules.PersonInterests", "PersonInterests")
                        .WithMany("Links")
                        .HasForeignKey("PersonId", "InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonInterests");
                });

            modelBuilder.Entity("WebbAPI.Modules.PersonInterests", b =>
                {
                    b.HasOne("WebbAPI.Modules.Interests", "Interest")
                        .WithMany("PersonInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebbAPI.Modules.Person", "Person")
                        .WithMany("PersonInterests")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("WebbAPI.Modules.Interests", b =>
                {
                    b.Navigation("PersonInterests");
                });

            modelBuilder.Entity("WebbAPI.Modules.Person", b =>
                {
                    b.Navigation("PersonInterests");
                });

            modelBuilder.Entity("WebbAPI.Modules.PersonInterests", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
